### ISSUE TITLE
Not able to find schema file 

### ISSUE THREAD

**Issue by rohithgoud10** [farmdawgnation/registryless-avro-converter#13]
When we give schema path as a s3 file path , It is saying FileNotFound . Tried with below paths
`s3:/path/to/ClientDhcpInfo.avsc`
`s3a:/path/to/ClientDhcpInfo.avsc`

It fails with error: [Worker-09e85a3f7686acb44] Caused by: java.io.FileNotFoundException: s3a:/path/to/ClientDhcpInfo.avsc (No such file or directory)

**Comment by farmdawgnation** [comment]
This is a duplicate of #14
