### ISSUE TITLE
FileNotFoundException With s3 schema path

### ISSUE THREAD

**Issue by spider-123-eng** [farmdawgnation/registryless-avro-converter#14]
Hi @farmdawgnation ,
we are seeing below error when we set the schema path to s3 as we are running s3 connector in AWS MSK
Can you please help us here ?

[Worker-069cb11002ccf12f5]**Caused by: java.io.FileNotFoundException: s3:/<bucket_name>/ClientDhcpInfo.avsc (No such file or directory)**

[Worker-069cb11002ccf12f5] 	at java.base/java.io.FileInputStream.open0(Native Method)
[Worker-069cb11002ccf12f5] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
[Worker-069cb11002ccf12f5] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[Worker-069cb11002ccf12f5] 	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1029)
[Worker-069cb11002ccf12f5] 	at org.apache.avro.Schema$Parser.parse(Schema.java:1396)
[Worker-069cb11002ccf12f5] 	at me.frmr.kafka.connect.RegistrylessAvroConverter.configure(RegistrylessAvroConverter.java:58)

key.converter.schema.path=s3://<bucket_name>/ClientDhcpInfo.avsc
value.converter.schema.path=s3://<bucket_name>/ClientDhcpInfo.avsc

**Comment by farmdawgnation** [comment]
Hi there,

I don't think this would have ever worked. The converter expects the schema to be available locally and uses a regular `FileInputStream` to try and access it. This could be extended to add support for S3 but that would be a new feature, I think.

**Comment by farmdawgnation** [comment]
I've filed #15 representing the feature request here.
