### ISSUE TITLE
registryless-avro-converter : message is not coming in avro format

### ISSUE THREAD

**Issue by themountainofgod** [farmdawgnation/registryless-avro-converter#4]
Hi Matt,

Thanks for registryless-avro-converter. I wrote one avro serializer and able to send the serialized message to kafka topic, my consumer side is able to deserialize the message. The data(byte) which i am getting in my deserializer has some extra character which i think is because of avro format.

However, when I used registryless-avro-converter and configured it to read the message from the same topic, the value(byte) in toConnectData(String topic, byte[] value), has the plain message and its in very text format. because of that, its failing in deserialization.
I was expecting the message from Kafka topic to be in same format as it coming for my custom consumer.

Can you please guide me here,if i am missing anything? or let me know if my question is not clear.

Thanks & regards
Ashish Shukla

**Comment by farmdawgnation** [comment]
It sounds a bit like something isn't configured correctly. Is there any chance you have some time to set up an example project on GitHub that demonstrates the issue you're seeing? If not, even a diagram of some sort for me to get an accurate picture of what you've got going on would be helpful! :)

**Comment by themountainofgod** [comment]
![image](https://user-images.githubusercontent.com/49004441/55200284-ba999c80-517a-11e9-9dd7-9ffa0624a5ef.png)

**Comment by themountainofgod** [comment]
The issue was with the configuration indeed. It was pointing to the wrong avsc file. Thanks!

**Comment by farmdawgnation** [comment]
Glad you got it sorted out! Cheers!
